import Link from "next/link";
import type { Progress, Roadmap, RoadmapTask } from "@/lib/api";

const KIND_BADGE: Record<string, string> = {
  lesson: "bg-blue-100 text-blue-900",
  exercise: "bg-emerald-100 text-emerald-900",
  quiz: "bg-amber-100 text-amber-900",
  project: "bg-purple-100 text-purple-900",
  interview: "bg-rose-100 text-rose-900",
  revision: "bg-slate-100 text-slate-900"
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function extractTopicFromTask(task: RoadmapTask): string | null {
  // Tasks generated by the backend look like "Phase title: Topic" for lessons
  // and "Topic — practice exercise" for exercises. We extract the topic name
  // so dashboard tasks can deep-link to the lesson page.
  if (task.kind === "lesson") {
    const colon = task.title.indexOf(":");
    if (colon >= 0) return task.title.slice(colon + 1).trim();
  }
  if (task.kind === "exercise") {
    const dash = task.title.indexOf("—");
    if (dash >= 0) return task.title.slice(0, dash).trim();
  }
  return null;
}

export function RoadmapSummary({
  roadmap,
  progress
}: {
  roadmap: Roadmap;
  progress: Progress | null;
}) {
  const plan = roadmap.generated_plan;
  const today = plan.daily_tasks.filter((t) => t.day === 1);
  const completionPct = progress?.completion_percentage ?? roadmap.completion_percentage;

  return (
    <div className="grid gap-6 md:grid-cols-3">
      <div className="md:col-span-2 space-y-4 rounded-lg border border-border p-6">
        <div>
          <h2 className="text-xl font-semibold">Today&apos;s plan</h2>
          <p className="text-sm text-muted-foreground">{plan.summary}</p>
        </div>
        <ul className="divide-y divide-border">
          {today.map((task, i) => {
            const topic = extractTopicFromTask(task);
            const slug = topic ? slugify(topic) : null;
            const linkable = slug && (task.kind === "lesson" || task.kind === "exercise");
            const inner = (
              <div className="flex items-center gap-3">
                <span
                  className={
                    "inline-block rounded px-2 py-0.5 text-xs font-medium " +
                    (KIND_BADGE[task.kind] ?? "bg-slate-100 text-slate-900")
                  }
                >
                  {task.kind}
                </span>
                <span className="text-sm">{task.title}</span>
              </div>
            );
            return (
              <li key={i} className="flex items-center justify-between py-3">
                {linkable ? (
                  <Link
                    href={`/learn/${slug}`}
                    className="flex-1 hover:underline underline-offset-4"
                  >
                    {inner}
                  </Link>
                ) : (
                  inner
                )}
                <span className="text-xs text-muted-foreground">{task.estimated_minutes} min</span>
              </li>
            );
          })}
        </ul>
        <Link href="/roadmap" className="text-sm text-primary underline-offset-4 hover:underline">
          View full roadmap →
        </Link>
      </div>

      <div className="space-y-4 rounded-lg border border-border p-6">
        <h3 className="font-semibold">Progress</h3>
        <div>
          <div className="text-3xl font-semibold">{Math.round(completionPct)}%</div>
          <div className="text-sm text-muted-foreground">
            {progress
              ? `${progress.completed_topics} of ${progress.total_topics} topics complete`
              : "Plan completion"}
          </div>
        </div>
        <div>
          <div className="text-3xl font-semibold">Phase {roadmap.current_phase}</div>
          <div className="text-sm text-muted-foreground">
            {plan.phases.find((p) => p.phase === roadmap.current_phase)?.title ?? "—"}
          </div>
        </div>
        <div>
          <div className="text-3xl font-semibold">{plan.phases.length}</div>
          <div className="text-sm text-muted-foreground">Phases ahead</div>
        </div>
      </div>
    </div>
  );
}
